#!/usr/bin/python3


def raise_exception():
    print("{:d}".format([4, 6, 2, 7]))
